apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgcat.fullname" . }}
  labels:
    {{- include "pgcat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgcat
      protocol: TCP
      name: pgcat
    - port: {{ .Values.configuration.general.prometheus_exporter_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "pgcat.selectorLabels" . | nindent 4 }}
