{
 "title": "PgCat Dashboard",
 "description": "A dashboard to monitor PgCat deployments. It is based on the metrics exported by the Prometheus exporter that comes bundled with PgCat\n\nPlease visit https://github.com/postgresml/pgcat for more information ",
 "tags": [
  "Databases",
  "PostgreSQL"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "role",
    "label": "Role",
    "query": {
     "query": "label_values(pgcat_databases_current_connections,role)"
    }
   },
   {
    "name": "shard_id",
    "label": "Shard ID",
    "query": {
     "query": "label_values(pgcat_databases_current_connections,shard)"
    }
   },
   {
    "name": "instance_index",
    "label": "Instance Index",
    "query": {
     "query": "label_values(pgcat_databases_current_connections,index)"
    }
   },
   {
    "name": "pool",
    "label": "Pool Name",
    "query": {
     "query": "label_values(pgcat_databases_current_connections,pool)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(pgcat_databases_current_connections,host)"
    }
   },
   { "name": "user", "label": "Username", "query": { "query": "label_values(usename)" } }
  ]
 },
 "panels": [
  { "title": "Throughput Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction Count",
   "type": "timeseries",
   "description": "For this metric, each individual query outside a transaction is counted as one transaction. All queries that run inside a transaction are counted as one transaction.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(pgcat_servers_transaction_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}[1m])",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  {
   "title": "Query Count",
   "type": "timeseries",
   "description": "The number of individual queries run",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "increase(pgcat_servers_query_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}[1m])",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  {
   "title": "Average Query Latency",
   "type": "timeseries",
   "description": "Average Query Latency",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgcat_stats_avg_query_time{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  {
   "title": "Average Transaction Latency",
   "type": "timeseries",
   "description": "Average latency of transactions",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pgcat_stats_avg_xact_time{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "timeseries",
   "description": "Data received in bytes",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(pgcat_servers_bytes_received{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}[1m])",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "timeseries",
   "description": "Data sent in bytes",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(pgcat_servers_bytes_sent{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}[1m])",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  { "title": "Capacity metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Percentage Server Pool Utilization",
   "type": "timeseries",
   "description": "This is the ratio between the number of active server connections to the pool size. Persistently high ratio (e.g. 80%-100%) may suggest the need for a larger pool or a more performant Database",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(pgcat_servers_active_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"} / pgcat_databases_pool_size{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}) * 100  ",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  {
   "title": "Waiting Clients",
   "type": "timeseries",
   "description": "The number of Clients currently waiting in the queue waiting for a server connection to be assigned. This should remain close to 0. Any persistent deviation from zero means clients are blocked from querying the database",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "pgcat_pools_cl_waiting{pool=~\"$pool\", user=~\"$user\"}",
     "legendFormat": "Pool:{{pool}}, User:{{user}}"
    }
   ]
  },
  {
   "title": "Banned Connections",
   "type": "timeseries",
   "description": "Banned connections won't get queries routed to them until they are unbanned. Instances are unbanned after the ban timer expires or if all replicas in the pool are banned so they are all unbanned as a failsafe. Primary instances are never banned",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "pgcat_servers_is_banned{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  {
   "title": "Paused Connections",
   "type": "timeseries",
   "description": "Paused connection are connections that belong to pool that was paused by the administrator",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "pgcat_servers_is_paused{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  {
   "title": "Maximum wait time by Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(pgcat_pools_maxwait{pool=~\"$pool\", user=~\"$user\"} * 1000 * 1000) + pgcat_pools_maxwait_us{pool=~\"$pool\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}"
    }
   ]
  },
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Idle Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "pgcat_servers_idle_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  {
   "title": "Active Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "pgcat_servers_active_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  {
   "title": "Server Connection in Login State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "pgcat_servers_login_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  {
   "title": "Server Connection in Tested State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "pgcat_servers_tested_count{pool=~\"$pool\", role=~\"$role\", shard=~\"$shard_id\", index=~\"$instance_index\", host=~\"$host\", user=~\"$user\"}",
     "legendFormat": "host:{{host}}, identifier:{{role}}{{index}}, shard_id:{{shard}}, pool:{{pool}}, user:{{user}}"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Idle Clients",
   "type": "timeseries",
   "description": "The number of Clients currently connected but not assigned a server connection nor are they seeking one",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "pgcat_pools_cl_idle{pool=~\"$pool\", user=~\"$user\"}",
     "legendFormat": "Pool:{{pool}}, User:{{user}}"
    }
   ]
  },
  {
   "title": "Active Clients",
   "type": "timeseries",
   "description": "The number of Clients currently assigned a server connection",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "expr": "pgcat_pools_cl_active{pool=~\"$pool\", user=~\"$user\"}",
     "legendFormat": "Pool:{{pool}}, User:{{user}}"
    }
   ]
  },
  {
   "title": "Waiting Clients",
   "type": "timeseries",
   "description": "The number of Clients currently waiting in the queue waiting for a server connection to be assigned. This should remain close to 0. Any persistent deviation from zero means clients are blocked from querying the database",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "expr": "pgcat_pools_cl_waiting{pool=~\"$pool\", user=~\"$user\"}",
     "legendFormat": "Pool:{{pool}}, User:{{user}}"
    }
   ]
  }
 ]
}