SET SERVER ROLE TO 'primary';
SELECT 1;

SET SERVER ROLE TO 'replica';
SELECT 1;

SET SHARDING KEY TO '1234';
SET SERVER ROLE TO 'primary';
SELECT 1;

SET SERVER ROLE TO 'replica';
SET SHARDING KEY TO '4321';
SELECT 1;