name: release
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Build
        run: cargo build --release
      
      - name: upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pgcat
          path: target/release/pgcat